config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :create_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  get 'about', to: 'pages#about' 

  get "mail_send" => "users#send_email"
  # My Articles Code start  
    get "get_articles" => "articles#get_all_article"
    get "get_articles/add/view" => "articles#add_article_view"
    post "add_article" => "articles#article_add"
    get "get_articles/edit/:data" => "articles#edit_article"
    post "update_article" => "articles#article_updated"
    get "get_articles/delete/:data" => "articles#delete_article"
  # My Articles Code end

  # My Articles Code start  
    get  "categories" => "categories#view_all_categories"  
    get  "add/new/category" => "categories#view_add_category"
    post "category/add" => "categories#add_category"  
    get  "category/edit/:catname" => "categories#edit_category" , as: 'category_edit'
    post "category/update" => "categories#update_category"
    get  "category/delete/:catname" => "categories#delete_category" , as: 'category_delete'
  # My Articles Code end


  resources :articles
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/controllers/create_blogs_controller.rb
class CreateBlogsController < ApplicationController
  before_action :set_create_blog, only: %i[ show edit update destroy ]

  # GET /create_blogs or /create_blogs.json
  def index
    @create_blogs = CreateBlog.all
  end

  # GET /create_blogs/1 or /create_blogs/1.json
  def show
  end

  # GET /create_blogs/new
  def new
    @create_blog = CreateBlog.new
  end

  # GET /create_blogs/1/edit
  def edit
  end

  # POST /create_blogs or /create_blogs.json
  def create
    @create_blog = CreateBlog.new(create_blog_params)

    respond_to do |format|
      if @create_blog.save
        format.html { redirect_to @create_blog, notice: "Create blog was successfully created." }
        format.json { render :show, status: :created, location: @create_blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @create_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_blogs/1 or /create_blogs/1.json
  def update
    respond_to do |format|
      if @create_blog.update(create_blog_params)
        format.html { redirect_to @create_blog, notice: "Create blog was successfully updated." }
        format.json { render :show, status: :ok, location: @create_blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @create_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_blogs/1 or /create_blogs/1.json
  def destroy
    @create_blog.destroy
    respond_to do |format|
      format.html { redirect_to create_blogs_url, notice: "Create blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_blog
      @create_blog = CreateBlog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_blog_params
      params.fetch(:create_blog, {})
    end
end

app/helpers/create_blogs_helper.rb
module CreateBlogsHelper
end

app/views/create_blogs/_form.html.erb
<%= form_with(model: create_blog, local: true) do |form| %>
  <% if create_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create_blog.errors.count, "error") %> prohibited this create_blog from being saved:</h2>

      <ul>
      <% create_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/create_blogs/edit.html.erb
<h1>Editing Create Blog</h1>

<%= render 'form', create_blog: @create_blog %>

<%= link_to 'Show', @create_blog %> |
<%= link_to 'Back', create_blogs_path %>

app/views/create_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_blogs.each do |create_blog| %>
      <tr>
        <td><%= link_to 'Show', create_blog %></td>
        <td><%= link_to 'Edit', edit_create_blog_path(create_blog) %></td>
        <td><%= link_to 'Destroy', create_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create Blog', new_create_blog_path %>

app/views/create_blogs/new.html.erb
<h1>New Create Blog</h1>

<%= render 'form', create_blog: @create_blog %>

<%= link_to 'Back', create_blogs_path %>

app/views/create_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_create_blog_path(@create_blog) %> |
<%= link_to 'Back', create_blogs_path %>