config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :create_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  get 'about', to: 'pages#about' 

  get "mail_send" => "users#send_email"
  # My Articles Code start  
    get "get_articles" => "articles#get_all_article"
    get "get_articles/add/view" => "articles#add_article_view"
    post "add_article" => "articles#article_add"
    get "get_articles/edit/:data" => "articles#edit_article"
    post "update_article" => "articles#article_updated"
    get "get_articles/delete/:data" => "articles#delete_article"
  # My Articles Code end

  # My Articles Code start  
    get  "categories" => "categories#view_all_categories"  
    get  "add/new/category" => "categories#view_add_category"
    post "category/add" => "categories#add_category"  
    get  "category/edit/:catname" => "categories#edit_category" , as: 'category_edit'
    post "category/update" => "categories#update_category"
    get  "category/delete/:catname" => "categories#delete_category" , as: 'category_delete'
  # My Articles Code end


  resources :articles
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/models/category.rb
class Category < ApplicationRecord
 	
 	before_save {self.name = name.downcase}

 	validates :name, presence: true

 	validates_uniqueness_of :name	

 	has_many :articles, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_same_user, only: [:view_all_categories, :view_add_category, :add_category, :edit_category, :update_category, :delete_category]

	def view_all_categories
		@categories = Category.all
		render "categories/view"
	end


	def view_add_category
		
		# @categories = Category.new		

		render "add_view"	
	end

	def add_category
		@category_name = params[:name]		
		
		@categories = Category.new(name: @category_name)
		if @categories.save
			flash[:notice] = "Category Added Successfully"
			redirect_to categories_path
		else
			render :add_view
		end
	end


	def edit_category
		@category_name = params[:catname]		
	
		@categories = Category.find_by(name: @category_name)

		render "categories/edit_view"	
	end

	def update_category
		@category_id = params[:id]
		
		@categories = Category.update(@category_id, name: params[:name])
		
		if @categories
			flash[:notice] = "Category Updated Successfully"
			redirect_to categories_path
		else
			render :edit
		end
	end

	def delete_category
		@category_name = params[:catname]		
		
		@cate_data = Category.find_by(name: @category_name)

		Category.destroy(@cate_data.id)

		#Category.where(name: @category_name).destroy_all

		flash[:notice] = "Category Deleted Successfully"
		redirect_to categories_path
	end
	
	def require_same_user
		if !current_user.admin?
			flash[:alert] = "You Are Not Admin"
			redirect_to root_path
		end	
	end

end

app/views/categories/add_view.html.erb
<h2>Add Article</h2></br>

<% if @categories.present? && @categories.errors.any? %>

	<p>Erros! Please Check...</p>
	<ul>
		<% @categories.errors.full_messages.each do |msg|%>
			<li> <%= msg %> </li>
		<% end %>
	</ul>
<% end %>

<a href="<%= categories_path %>">View All Categories</a>

</br>

<form id="article_add_form" action="<%= category_add_path %>" method="POST">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	
	<div style="display: flex; margin: 10px; justify-content: space-around;">
		<label>Category Name :</label>
		<input type="text" name="name">
	</div>
	<div style="display: flex; margin: 10px; justify-content: center;">
		<input name="save" type="submit" value="Add" />
	</div>
</form>

app/views/categories/edit_view.html.erb
<h2>Details</h2></br>

<% if @categories.present? && @categories.errors.any? %>

	<p>Erros! Please Check...</p>
	<ul>
		<% @categories.errors.full_messages.each do |msg|%>
			<li> <%= msg %> </li>
		<% end %>
	</ul>
<% end %>

<a href="<%= categories_path %>">View All Categories</a>

</br>
</br>
<form accept-charset="UTF-8" action="<%= category_update_path %>" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<label>Title :</label>

	<input type="hidden" name="id" value="<%= @categories.id %>">
	<div style="display: flex; margin: 10px; justify-content: space-around;">
		<input type="text" name="name" value="<%= @categories.name %>">
	</div>
	<div style="display: flex; margin: 10px; justify-content: center;">
		<input name="update" type="submit" value="Update" />
	</div>
</form>

app/views/categories/view.html.erb
<br>
<br>
<br>
<a href="/add/new/category">Add Category</a>
<table border="1">	
	<tr>
		<th>srno.</th>
		<th>Name</th>
		<th>Delete</th>
	</tr>
	<% @categories.each_with_index do |t,i| %>
		<tr>
			<td> No : <%= i %></td>
			<td> Name : <a href="<%= category_edit_path t.name %>"> <%= t.name %></a></td>			
			<td> <a href="<%= category_delete_path t.name %>" onclick="return confirm('Are you sure?')"> Delete</a></td>
		</tr>
	<% end %> 			
</table>