config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :create_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  get 'about', to: 'pages#about' 

  get "mail_send" => "users#send_email"
  # My Articles Code start  
    get "get_articles" => "articles#get_all_article"
    get "get_articles/add/view" => "articles#add_article_view"
    post "add_article" => "articles#article_add"
    get "get_articles/edit/:data" => "articles#edit_article"
    post "update_article" => "articles#article_updated"
    get "get_articles/delete/:data" => "articles#delete_article"
  # My Articles Code end

  # My Articles Code start  
    get  "categories" => "categories#view_all_categories"  
    get  "add/new/category" => "categories#view_add_category"
    post "category/add" => "categories#add_category"  
    get  "category/edit/:catname" => "categories#edit_category" , as: 'category_edit'
    post "category/update" => "categories#update_category"
    get  "category/delete/:catname" => "categories#delete_category" , as: 'category_delete'
  # My Articles Code end


  resources :articles
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/views/layouts/_msgs.html.erb
<% flash.each do |name, msg|%>
	<div class="alert alert-success m-4" role="alert">
		<%= msg %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
<% end %>	

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" id="logo" href="/">ALPHA BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class: 'nav-link' %>
          </li>
          <% if logged_in? && current_user.admin? %>
            <li class="nav-item">
              <a href="<%= categories_path %>" class="nav-link">Categories</a>
              <%#= link_to 'Articles', articles_path, class: 'nav-link' %>
            </li>
          <% end %>
          
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">     
                <%= link_to 'Delete Profile', user_path(current_user), method: :Delete, data: {confirm:"Are You Sure You want Delete This?"}, class: "dropdown-item" %>           
                <%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item"%>
                <%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %>   

              </div>
            </li>
            <!-- <li class="nav-item">
              <%= link_to current_user.username, user_path(current_user), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
            </li> -->
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', signup_path, class: "nav-link"%>
            </li>
          <% end %>

          <% if logged_in? && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/nav' %>
    <div class="container" id="home-container">
      <%= render 'layouts/msgs' %>
      <%= yield %>
    </div>
    <%= render 'pages/footer' %>
  </body>
</html>